trigger:
  branches:
    include:
      - main
      - release/*

resources:
  containers:
    - container: Redis
      image: redis
      ports:
        - 6379:6379
  repositories:
    - repository: self

variables:
  buildConfiguration: Release

  root: "$(Build.SourcesDirectory)"
  buildProject: "$(root)/build/TwoTierCache.Build/TwoTierCache.Build.csproj"

  vmImageName: "ubuntu-latest"
  
  disable.coverage.autogenerate: 'true'

stages:
  - stage: Build
    displayName: Build and publish stage
    jobs:
      - job: Build
        displayName: Build and publish
        pool:
          vmImage: $(vmImageName)
        services:
          Azurite: Redis
        steps:          
          - task: UseDotNet@2
            displayName: "Use .NET Core 6"
            inputs:
              version: "6.x"
          - task: DotNetCoreCLI@2
            displayName: Restore
            inputs:
              command: restore
              projects: $(buildProject)
          - task: DotNetCoreCLI@2
            displayName: Build
            inputs:
              projects: $(buildProject)
              arguments: '--configuration $(buildConfiguration) --no-restore'
          - task: DotNetCoreCLI@2
            displayName: Test
            inputs:
              command: test
              projects: $(buildProject)
              arguments: '--configuration $(buildConfiguration) --no-build --no-restore --collect:"XPlat Code Coverage" --settings $(root)/coverlet.runsettings.xml'
          - task: DotNetCoreCLI@2
            displayName: 'Install ReportGenerator'
            inputs:
              command: custom
              custom: tool
              arguments: 'install --global dotnet-reportgenerator-globaltool'        
          - script: reportgenerator "-reports:$(Agent.TempDirectory)/**/coverage.cobertura.xml" "-targetdir:$(root)/code_coverage" "-reporttypes:HtmlInline_AzurePipelines;Cobertura"
            displayName: Merge code coverage files
          - task: PublishCodeCoverageResults@1
            inputs:
              codeCoverageTool: 'cobertura'
              summaryFileLocation: '$(root)/code_coverage/*.xml'
              reportDirectory: '$(root)/code_coverage'
          - task: DotNetCoreCLI@2
            displayName: Pack
            condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))
            inputs:
              command: pack
              packagesToPack: '$(root)/src/**/*.csproj'
              arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory) --no-restore'
              nobuild: true
              versioningScheme: 'off'
          - task: CmdLine@2
            displayName: Push
            inputs:
              script: 'dotnet nuget push *.nupkg --api-key $(nugetApiKey) --source https://api.nuget.org/v3/index.json --skip-duplicate'
              workingDirectory: '$(Build.ArtifactStagingDirectory)'
          - task: PublishBuildArtifacts@1
            inputs:
              PathtoPublish: "$(Build.ArtifactStagingDirectory)"
              ArtifactName: "drop"
              publishLocation: "Container"
              